### ISSUE TITLE
Port to ROS 2 

### ISSUE THREAD

**Issue by Ryanf55** [ethz-asl/grid_map_geo#23]
I'd like to use this in ROS 2 to support the SmartRTL feature in ArduPilot. Please assign me this issue, and I'll issue a PR for the port to ROS 2 as soon as it's ready.

Since grid_map already has ROS 2 support, nothing is blocking this work.

In scope:

- [ ] Replace catkin with colcon
- [ ] Update roscpp with rclcpp
- [ ] Update README for ROS 2 usage
- [ ] Modernize CMake for CMake 3.12 features
- [ ] Remove compile warnings/errors that show up in GCC11 (Ubuntu 22)
- [ ] Works on Humble

Later:

- [ ] Releasing binaries to the ROS build farm with bloom
- [ ] CI

**Comment by Ryanf55** [comment]
Hello,

Can you share where I can find the following two files?

- resources/sertig.tif
- resources/sertig_color.tif

They are specified in the launch file, but do not appear to be tracked in the repo. 

Many thanks!

**Comment by Jaeyoung-Lim** [comment]
@Ryanf55 Sorry that it seems that we have been doing redundant work. 
This package has already been ported into ROS2: https://github.com/Jaeyoung-Lim/grid_map_geo2

With the tif files, this should work with any files with geotiff format. I would need to review the license of the geotiff files before releasing them in public. I will invite you to the repository just in case.

**Comment by srmainwaring** [comment]
Largely completed by #24, #26, #27.

The remaining tasks concerning CI and packaging for ROS 2 release could be moved to independent follow up issues?
