### ISSUE TITLE
test_grid_map_geo.launch is not valid in the repo

### ISSUE THREAD

**Issue by Kucukcollu** [ethz-asl/grid_map_geo#5]
Hi,

I wanted to test the project so I setup the project as you describe in the repository but "test_grid_map_geo.launch" is not valid in the repo for the demo.

thanks.

**Comment by Jaeyoung-Lim** [comment]
@Kucukcollu Thanks for trying out the project. As you pointed out, the readme is referring to the wrong launchfile that is not part of this repository. The issue should be solved with the following PR: https://github.com/ethz-asl/grid_map_geo/pull/4/files

**Comment by Jaeyoung-Lim** [comment]
Closing as there was no response and the issue was resolved.

@Kucukcollu Please feel free to reopen if you think this is still an issue
