### ISSUE TITLE
Python Launch: Switch from os to pathlib

### ISSUE THREAD

**Issue by Ryanf55** [ethz-asl/grid_map_geo#54]
# Purpose

The pathlib library is more `pythonic` than calling `os.path` for managings paths.

Currently, `launch/load_tif.launch.py` uses the `os` module. let's switch to pathlib. 

# How to run it 

```bash
colcon build --packages-up-to grid_map_geo
source install/setup.bash
ros2 launch grid_map_geo load_tif.launch.py
```

# Required tests

- [x] Switch to pathlib
- [x] Share terminal output of successful launch
- [x] Add the above steps to the README because it's missing

**Comment by MichaelRazum** [comment]
Happy to do the issue.

**Comment by MichaelRazum** [comment]
Terminal output:
![image](https://github.com/ethz-asl/grid_map_geo/assets/6819881/9a17fb04-3d23-4869-98ea-5d57a69d0f25)
