### ISSUE TITLE
no data in eleveation map

### ISSUE THREAD

**Issue by Ahmad-Drak** [ethz-asl/grid_map_geo#6]
Hi,
Thanks for the nice package. However the alligning doesnt seem to work in my case

```
SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.14
 * /test_tif_loader/tif_path: /home/ahmad/works...

NODES
  /
    rviz (rviz/rviz)
    test_tif_loader (grid_map_geo/test_tif_loader)
    world_map (tf/static_transform_publisher)

auto-starting new master
process[master]: started with pid [236172]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 9280e2fe-1700-11ed-b6a4-7b9e3271b9fe
process[rosout-1]: started with pid [236213]
started core service [/rosout]
process[world_map-2]: started with pid [236216]
process[test_tif_loader-3]: started with pid [236217]
process[rviz-4]: started with pid [236222]

Loading GeoTIFF file for gridmap

Wkt ProjectionRef: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
Width: 3139 Height: 3361 Resolution: 1.43701e-06
[GridMapGeo] Not aligning terrain!

```

this refers to https://github.com/ethz-asl/grid_map_geo/blob/4a14be7084111f822cd6ae852981dfe0d829b570/src/grid_map_geo.cpp#L112 
but i dont understand what you are doing in the lines above that..

**Comment by Ahmad-Drak** [comment]
The 'not aligining' is not an error it seems. A false flag is passed here
https://github.com/ethz-asl/grid_map_geo/blob/4a14be7084111f822cd6ae852981dfe0d829b570/src/test_tif_loader.cpp#L64

However in rviz all i see is an empty grid, nothing else

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak Have you tried setting the path to a tif file in https://github.com/ethz-asl/grid_map_geo/blob/4a14be7084111f822cd6ae852981dfe0d829b570/launch/load_tif.launch#L6 ?

Unfortunately there is no tif file included in this repository yet due to license constraints

**Comment by Ahmad-Drak** [comment]
i added my own tif file
`<param name="tif_path" value="$(find grid_map_geo)/resources/DTM-100mm.tif"/>`

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak Ah, I see the problem now

You need to provide an empty path for https://github.com/ethz-asl/grid_map_geo/blob/4a14be7084111f822cd6ae852981dfe0d829b570/launch/load_tif.launch#L7

I will fix this in a following PR

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim i did as you suggest, same result
```
<param name="tif_path" value="$(find grid_map_geo)/resources/DTM-100mm.tif"/>
 <param name="color_path" value=""/>
```

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak Have you checked if your rviz is properly configured to visualize the terrain? It should look like below

![image](https://user-images.githubusercontent.com/5248102/183401294-38873f6a-b56a-4d44-8b8e-29a6e9fda2a7.png)

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim it looks just like yours, without the last 3 options

![Screenshot from 2022-08-08 12-52-22](https://user-images.githubusercontent.com/8726349/183402052-ca664e1f-1645-4e34-b48f-64b5199df55d.png)

When checking the topic `/elevation_map`, there is nothing published there

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak Actually if you look at the Color Transformer, they are not the same. Can you try changing them as displayed in the screenshot I sent you?

Otherwise if you can send the elevation map over I can have a look what is going on

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim even when chosing Color transformer as Intensity Layer its still same result.
You can get the tif file here https://ufile.io/sa7q81l6

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak For the DEM you have produced, I am experiencing the same.

Looking into the tif file you shared, is it correct that your model has such a small resolution? 
```
Width: 3139 Height: 3361 Resolution: 1.43701e-06
```

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim yes, thats correct. Its a very high resolution dem

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak I think this is outside the test case I was aware of, but looking into what is going on, it seems like due to the distance transform it has been doing https://github.com/ethz-asl/grid_map_geo/blob/4a14be7084111f822cd6ae852981dfe0d829b570/src/grid_map_geo.cpp#L56 it is simply taking too long to compute the distance surface. 

For your use case I have removed this in

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim Thank you for the quick fix. However still doesnt show up on my end. I pulled the changes and build again. The results is same as before. The Color Layer entry in rviz only has 'color' option, not elevation like yours.
I think this is because the `/elevation_map` topic is still not publishing..

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim interestingly, this does not show up in the terminal

https://github.com/ethz-asl/grid_map_geo/blob/52025cee8bdbd09a15942596b406a39f7aebe4c0/src/grid_map_geo.cpp#L146

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak How long did you wait for the dem to be read?

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim the node is still running. Its been at least 8 minutes.

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak The only thing I can think of is the performance of the system

For me it takes a few seconds(3-4) to read your dem

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim thats unlikely, Im using a Ryzen 9 5950x.
I will try to debug more somehow

**Comment by Ahmad-Drak** [comment]
@Jaeyoung-Lim ughhhh! Sorry, my bad! I didn't source my other devel directory *face palm*.
It works now, I get a red line going through the grid. I assume thats because of my original dem,
Thank you for the efforts!

**Comment by Jaeyoung-Lim** [comment]
@Ahmad-Drak Happy to hear that it worked out!

**Comment by Ahmad-Drak** [comment]
just for reference, it was showing a line only since my original tif file was in wgs84. hence the pixel size was in degrees not meters. Therefore it was showing as 3mmx3mm 'line' in rviz.
